[build]
builder = "NIXPACKS"
buildCommand = "cd api && npm install && npx prisma generate && npm run build"

[deploy]
startCommand = "cd api && bash start.sh"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
